// set loading
const ON_LOADING = 'ON_LOADING';
const OFF_LOADING = 'OFF_LOADING';

// get products
const GET_ALL_DATA = 'GET_ALL_DATA';
const PAGE_PER_DATA = 'PAGE_PER_DATA';
const FILTERED_DATA = 'FILTERED_DATA';

const REGION_DATA = 'REGION_DATA';

// input
const HANDLE_INPUT = 'HANDLE_INPUT';

export {
  GET_ALL_DATA,
  PAGE_PER_DATA,
  FILTERED_DATA,
  ON_LOADING,
  OFF_LOADING,
  HANDLE_INPUT,
  REGION_DATA,
};
