// set loading
const ON_LOADING = 'ON_LOADING';
const OFF_LOADING = 'OFF_LOADING';

// get products
const GET_ALL_DATA = 'GET_ALL_DATA';
const PAGE_PER_DATA = 'PAGE_PER_DATA';
const FILTERED_DATA = 'FILTERED_DATA';

const REGION_DATA = 'REGION_DATA';

// input, reset
const HANDLE_INPUT = 'HANDLE_INPUT';
const HANDLE_RESET = 'HANDLE_RESET';

// message
const INPUT_MSG = 'INPUT_MSG';
const CLOSE_ALERT = 'CLOSE_ALERT';
const NO_DATA_ALERT = 'NO_DATA_ALERT';

// region data
const REGION_ON_LOADING = 'REGION_ON_LOADING';
const REGION_ALL_DATA = 'REGION_ALL_DATA';
const REGION_PER_PAGE = 'REGION_PER_PAGE';
const REGION_FILTERED_DATA = 'REGION_FILTERED_DATA';
const REGION_OFF_LOADING = 'REGION_OFF_LOADING';
const CATEGORY_PRODUCTS = 'CATEGORY_PRODUCTS';

export {
  GET_ALL_DATA,
  PAGE_PER_DATA,
  FILTERED_DATA,
  ON_LOADING,
  OFF_LOADING,
  HANDLE_INPUT,
  REGION_DATA,
  INPUT_MSG,
  CLOSE_ALERT,
  HANDLE_RESET,
  NO_DATA_ALERT,
  REGION_ON_LOADING,
  REGION_ALL_DATA,
  REGION_PER_PAGE,
  REGION_FILTERED_DATA,
  REGION_OFF_LOADING,
  CATEGORY_PRODUCTS,
};
